### ISSUE TITLE
Transition image et "seek-bar" quand la musique change

### ISSUE THREAD

**Issue by quentin3157** [busybox11/NowPlaying-for-Spotify#1]
Cce serai pas mal d'avoir une transition d'image pour la pochette et le background quand la musique change car actuellement quand la musique change le fond et la pochette deviennent blanche d'un coup(le temps que la nouvelle image charge pour les petites connexions) puis ils rechangent pour mettre la nouvelle pochette.
je sais que pour les règles background-* on peut pas appliquer de transitions, donc tu pourrait à la place de mettre un background, ajouter un <img style="width:100% height:100%;"> dans #background-image-div

Au niveau de la seek-bar, juste ajouter en css transition: linear width 0.1s; dans #seekbar-now (j'ai tester ça marche nickel)

**Comment by busybox11** [comment]
Je viens d'ajouter la transition sur le site, mais je ne vois pas de changement...
Pourrais-tu envoyer le code CSS que tu as modifié ?

Sinon, je modifie le Readme avec ta suggestion, merci !

**Comment by quentin3157** [comment]
Je close car le site a maintenant ces fonctionnalités
