### ISSUE TITLE
fichier .htaccess absent

### ISSUE THREAD

**Issue by SexiestCHiba** [busybox11/NowPlaying-for-Spotify#11]
Étant donné que le fichier est absent, le serveur ne redirige pa les utilisateurs vers les la page error/404.php quand l'url n'est pas bonne.
Il peut être interressant de mettre ce fichier pour indique à php de ne pas affiché les erreurs avec `php_flag display_errors Off` ou metre 
```
php_flag display_errors On
php_value error_reporting E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
```
pour qu'il n'affiche que les erreurs critiques ou fatales

**Comment by busybox11** [comment]
Je te laisse faire un commit, sinon tu n'apparaîtra pas comme contributeur, mais merci !

**Comment by SexiestCHiba** [comment]
C'était pas nécessaire de fermer l'issue, elle se ferme toute seul si on met `fix #id` dans les titres ou descriptions de commit.
