### ISSUE TITLE
Sur Téléphone, le bouton plein écran ne permet pas de quitter le plein écran

### ISSUE THREAD

**Issue by SexiestCHiba** [busybox11/NowPlaying-for-Spotify#15]
Lorsqu'on clique sur plein écran, le navigateur réagit normalement et met la page en plein écran mais quand on reclique dessus alors qu'on est déjà en plein écran, celui-ci ne s'enlève pas

Version: Chrome Mobile 69.0

Je précise qu'il fonctionne correctement sur les navigateurs desktop

**Comment by busybox11** [comment]
Je peux pas vraiment remédier à ça, normalement y'a pas encore cette fonctionnalité sur mobile
Tu devrais faire retour ou faire le geste pour afficher la barre de notifications

**Comment by SexiestCHiba** [comment]
Effectivement j'ai regardé de plus près ça me parait compliqué, je close
