### ISSUE TITLE
Device infos overflow on smaller screens

### ISSUE THREAD

**Issue by busybox11** [busybox11/NowPlaying-for-Spotify#30]
**Describe the bug**
Display bug with smaller screens

**Expected behavior**
There should not have any line breaks.

**Screenshots**
![image](https://user-images.githubusercontent.com/29630035/94129291-79f80d80-fe5b-11ea-9487-3f7413486c78.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 83

**Comment by SexiestCHiba** [comment]
I have 2 possible solutions: Smaller the text "Ready to cast on NowPlaying for Spotify" and the second, use a grid/flex for theirs 2 elements with the first have ~80% and second 20% and use per example: `overflow-wrap: break-word;` to avoid the text overflowing from his box

**Comment by busybox11** [comment]
Hey, I'm back. Do you have any other idea? 

I'd like to implement a scrolling effect but I haven't done this before so I'm currently searching how to do it, I'll update this issue with that.

**Comment by busybox11** [comment]
![image](https://user-images.githubusercontent.com/29630035/97504606-7d5d4800-1977-11eb-93b3-42c8d852d67c.png)
I think I'm gonna do something like this. I'll experiment it later.

**Comment by busybox11** [comment]
I totally haven't forgotten about this issue 😅 

![image](https://user-images.githubusercontent.com/29630035/112609379-c24cb400-8e1b-11eb-858a-2802b4d04916.png)
Here is it, it's not finished at all but it's been quite some time with the fix.
I'll try to improve this later on but I consider this aleady pretty good.
