### ISSUE TITLE
Use of a .env file

### ISSUE THREAD

**Issue by busybox11** [busybox11/NowPlaying-for-Spotify#31]
Currently, the only way to store Spotify credentials for the API is by editing two files (`token.php` and `login.php`).

A better solution would be to use a .env file, which will improve usability (e.g. automatic update deployment). Also, only one file will be modified instead of two.

**Comment by finnie2006** [comment]
@busybox11 
https://github.com/busybox11/NowPlaying-for-Spotify/pull/67

**Comment by VoXaN24** [comment]
It's resolved so
