### ISSUE TITLE
Too many playback fetches

### ISSUE THREAD

**Issue by FelixJohnsson** [busybox11/NowPlaying-for-Spotify#39]
Too many fetches. One song is sometimes over 500 fetches. 

Solution:
Guessing the playback state with intervals. Progressing the playing bar with an interval instead of fetching. Until the end of the songs length. Could decrease number of fetches every 30 seconds from 30 to 10 or even 3.

Or post on the forum about getting web sockets.

**Comment by busybox11** [comment]
I know this is a janky solution, but that's the only one we have that kinda looks like live-updated. Websockets are the #1 requested feature on their forum, a developer said that they were going to look into that. About 2 years ago (iirc).

I don't want to do something like that. You can seek through the music, skip, stop... I know this is a lot of fetches but we don't really have the choice if we want something "good".
Sorry, I will close your issue now.
