### ISSUE TITLE
Issue with arabic language

### ISSUE THREAD

**Issue by victorbnl** [busybox11/NowPlaying-for-Spotify#52]
In the sentence at the bottom it should probably not be `CONNECT TO SPOTIFY` but `Spotifyاتصل بـ`

![bildo](https://user-images.githubusercontent.com/39555268/128420306-772fbc25-e658-4a88-b813-d99d1171e6bf.png)

**Comment by VoXaN24** [comment]
Oh i have forget to translate it ! Thank's btw i made the change rn

**Comment by victorbnl** [comment]
You speak so many languages :o
