### ISSUE TITLE
Issue with arabic

### ISSUE THREAD

**Issue by victorbnl** [busybox11/NowPlaying-for-Spotify#54]
>  Parse error: syntax error, unexpected token "\", expecting ")" in C:\xampp\htdocs\assets\lang\ar.php on line 5

**Comment by victorbnl** [comment]
I think there are too much `'` here
> `\'Spotifyاتصل بـ' \'`

**Comment by VoXaN24** [comment]
Yes but no, like it's the fact it's in Arabic made that. It's the same amout has other... It's maybe for that i hvn't translated this part

**Comment by VoXaN24** [comment]
The issue is still present ?

**Comment by victorbnl** [comment]
Yes

**Comment by VoXaN24** [comment]
Crap, i think i just remove the "Connect to spotify" to something else

**Comment by victorbnl** [comment]
There's no need

**Comment by VoXaN24** [comment]
It's that part made the errors for an unknow reason

**Comment by victorbnl** [comment]
I changed `\' Spotifyاتصل بـ'  \'` to `\' Spotifyاتصل بـ \'` and it works. If you need two quotes after the "Login to Spotify" because the arabic language is made like that, just escape also the first one : `\' Spotifyاتصل بـ \' \'`

**Comment by victorbnl** [comment]
> 
> 
> It's that part made the errors for an unknow reason

I don't think you really needed to change the whole sentence just for this problem though, as I described above

**Comment by VoXaN24** [comment]
The PB, i don't modificate anything of the number of `'` , i think it just didn't like Arabic, the sentence has the same meaning btw

**Comment by VoXaN24** [comment]
Oh, Well i modificated back

**Comment by victorbnl** [comment]
> 
> 
> The PB, i don't modificate anything of the number of `'` , i think it just didn't like Arabic, the sentence has the same meaning btw

Ok but why does it work for me then? xD

**Comment by VoXaN24** [comment]
Idk that a mystery mate

**Comment by victorbnl** [comment]
Ok xD
Now it works anyway
