### ISSUE TITLE
Another problem with arabic

### ISSUE THREAD

**Issue by victorbnl** [busybox11/NowPlaying-for-Spotify#56]
I think you'll directly see the problem as you speak arabic and understand the sentence, and I don't, but I think there's another problem with RTL alignement here 

![bildo](https://user-images.githubusercontent.com/39555268/128426287-dc114f58-5b84-4ccc-b98b-7f42d82f4a1a.png)

**Comment by VoXaN24** [comment]
I look at it tomorrow it's seem the `'` want to travel in the sentence

**Comment by victorbnl** [comment]
I doesn't looks to me like it's only the `'` but a whole part of the text that wants to travel but I don't know

**Comment by VoXaN24** [comment]
That the problem when a language is right-writing, it's a nightmare for alignment

**Comment by VoXaN24** [comment]
It's the sentences we have problem from the start ... Litteraly now the sentence mean  -> By clicking "Contact", you accept the use of cookies necessary for the proper operation of the Spotify Website. ... That a non-sens i check that ASAP

**Comment by VoXaN24** [comment]
Normely, this time it's ok (maybe i have missplaced the `'` in the `'\ '\`

**Comment by victorbnl** [comment]
> That the problem when a language is right-writing, it's a nightmare for alignment

Yes I've seen that, even just for copy-pasting it selects things you don't want too and when there's english in the middle it's horrible.

**Comment by victorbnl** [comment]
![bildo](https://user-images.githubusercontent.com/39555268/128500098-834a2821-2071-4110-965b-bbab912577f7.png)

The text in `'` still doesn't seem to represent the button's text

**Comment by VoXaN24** [comment]
The text in the boton isn't accurate, it's ok now

**Comment by victorbnl** [comment]
![bildo](https://user-images.githubusercontent.com/39555268/128511222-73255d80-920a-400b-a51a-302e03875ae3.png)

It's still not the same thing

**Comment by victorbnl** [comment]
![bildo](https://user-images.githubusercontent.com/39555268/128511669-fd9a6918-2d6f-415a-90f3-07f7ba049934.png)

Also the `'` seems misplaced, I think you should remove the space to the right of it and put a space at the left, but maybe I'm wrong

**Comment by VoXaN24** [comment]
Normelly it's the same text btw i have made a c/c, and nope it's at the right place

**Comment by victorbnl** [comment]
Then I let you close the issue if it's fixed

**Comment by VoXaN24** [comment]
Fixed
