### ISSUE TITLE
Suggestion: svg for all flags

### ISSUE THREAD

**Issue by victorbnl** [busybox11/NowPlaying-for-Spotify#60]
If you agree I'll make a PR

**Comment by VoXaN24** [comment]
That can be a good thing, if you have the time why not ? Just pls change in the lang.php to 😀

**Comment by victorbnl** [comment]
Oki no problem

**Comment by VoXaN24** [comment]
Thanks mate

**Comment by VoXaN24** [comment]
I can't merged that weird
