### ISSUE TITLE
Domain down?

### ISSUE THREAD

**Issue by stephanebruckert** [busybox11/NowPlaying-for-Spotify#70]
Wanted to try this out but https://nowplayi.ng/:

> This site can’t be reached
> Check if there is a typo in nowplayi.ng.
> DNS_PROBE_FINISHED_NXDOMAIN

**Comment by busybox11** [comment]
Okay sooo... It appears that it will be more complicated than what I had in mind.
The domain is not very cheap and I wasn't aware of that, I don't have enough money to pay the renewal.
I'm trying to find a way to renew the domain anyway but it will maybe take some time.
I'm going to use this issue to track the progress of that.

**Comment by busybox11** [comment]
A temporary solution is up and running!
NPFS is currently also being hosted on [nowplaying.ga](http://nowplaying.ga/) (HTTP only for now). I'm trying to get the original domain back as soon as possible tho.

**Comment by VoXaN24** [comment]
Domain up
