### ISSUE TITLE
Artwork-only mode

### ISSUE THREAD

**Issue by stephanebruckert** [busybox11/NowPlaying-for-Spotify#71]
Hey @busybox11,

I'm using your project to project :-) my currently playing song on a wall using a raspberry pi:

<img src="https://user-images.githubusercontent.com/1932338/142492550-7a44553d-f235-4345-9965-48dea0709fe5.jpg" width="300">

However my initial goal was to only display the artwork, something like:

<img src="https://user-images.githubusercontent.com/1932338/142493147-a667c9e6-fd92-42ae-a70d-4ed622a92a0c.jpg" width="300">

Here is a prototype https://61969ee4bf0a8a8c486890f9--jovial-liskov-02cc5a.netlify.app/. That's basically the artwork using 100% height, centered vertically with a black background.

Would you be open to a PR that adds a mode to switch to artwork-only? I think your app is great and was thinking there is no point creating a new one!

Thank you

**Comment by VoXaN24** [comment]
You can made one, free to Busy to accept it or not,
Btw that not an issue, please use the correct thing for it

Issue Closed - Not an Issue

**Comment by stephanebruckert** [comment]
@VoXaN24 thanks for the response, however you're not helping by closing this. Feature requests go in the issues section.

I was specifically asking whether @busybox11 would be accepting a pull request that implements this and your answer is basically repeating the question

**Comment by VoXaN24** [comment]
> @VoXaN24 thanks for the response, however you're not helping by closing this. Feature requests go in the issues section.
> 
> I was specifically asking whether @busybox11 would be accepting a pull request that implements this and your answer is basically repeating the question

Read my anwser thanks

**Comment by stephanebruckert** [comment]
I would like the idea approved before I put in any work towards a PR

**Comment by VoXaN24** [comment]
Made a PR, we can reject it if we dont like or it has a problem with the Idea.
Btw Features idea must be made in the discord

**Comment by stephanebruckert** [comment]
I'll join the discord so we can discuss implementation details beforehand – thanks
