### ISSUE TITLE
Replace "Deutsche" with "Deutsch"

### ISSUE THREAD

**Issue by kevadesu** [busybox11/NowPlaying-for-Spotify#75]
**Describe the bug**
This isn't a bug, rather a mistake. On nowplaying (and many many other websites), the German language is referred to as "Deutsche" while it's actually "Deutsch" (or "deutsche Sprache" if you want to say "german language")

**To Reproduce**
1. Go to 'nowplayi.ng'
2. Hover over the german flag on the login page
3. It'll say "Deutsche" 

**Expected behavior**
Hovering over the german flag should say "Deutsch" instead of "Deutsche"

**Screenshots**
![image](https://user-images.githubusercontent.com/76264518/209821927-65fc2435-86b1-451f-82c2-002057f88798.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 36 (KDE Spin) (6.0.9-200.fc36.x86_64)
 - Browser: Firefox
 - Version 107.0 (64-Bit)

**Additional context**
That's all.

**Comment by busybox11** [comment]
Thanks for the feedback, I apologize for the late response!
Updating this rn.
