### ISSUE TITLE
Display does not fit fully in landscape mode on smartphone web browser

### ISSUE THREAD

**Issue by GGmarcGG** [busybox11/NowPlaying-for-Spotify#82]
**Describe the bug**
It works normally in Portrait mode when you use the full screen button
But when you are in Landscape mode, even in full screen mode, there are not all the elements on the same screen (cover, title, band, etc) 

**To Reproduce**
I test on android with firefox and chrome

Go on https://nowplayi.ng/ website with my phone
Turn my phone in Landscape mode
Push the full screen button

**Expected behavior**
All the elements on the same screen, like on desktop web browser

**Smartphone (please complete the following information):**
 - Device: Redmi 11S

**Comment by busybox11** [comment]
Hi!
Thanks for your report. Could you provide a screenshot of the website for this behavior please?
It will be easier for me to fix this with a visual report of what you're looking at.

**Comment by busybox11** [comment]
Hi, thank you for the screenshots! I'll try to fix this today :)

**Comment by GGmarcGG** [comment]
Hi !
Thanks for your work :) 
It works perfectly!
Thank you so much !!
